general:
  max_retries_intrinio: 20
  commit_database: True
  ignore_time: True

dbserver:
  uid: titus
  pwd: VDYCDuayE4ckRMcXbNcxWXkjDujABkTd2WyFZJc8HzZazd4rZN4K3SDyw3FrfBep2Gbae6c7nnMgaans6bKvQFxAbMuenjf3crPcM9ktaURrH273EG3CQC4dA
  host: apollo.chitk6thgemt.us-east-1.rds.amazonaws.com
  port: 5432

intrinio:
  api_key: OmRhYzhkZDc0ZTkyMTlhNmI1NmY0ZTEyYjNkODEwYjQ1
  sandbox_key: OmRhZDIzNTAwZTU3ODI5MDdhOWY2ZjFjN2IyMmQ0NWEy

S3:
  aws_access_key_id: AKIAU2WSHAXZR6LZLQMQ
  aws_secret_access_key: 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